1. What is a Python library? Why do we use Python libraries?

A Python library is a collection of modules and functions that provide pre-written code to perform specific tasks or functions. These libraries aim to simplify the development process by offering reusable and well-tested code, allowing developers to leverage existing solutions rather than starting from scratch.

Python libraries serve various purposes, such as:

Code Reusability: Libraries encapsulate commonly used functions and algorithms, making it easy for developers to reuse code instead of writing the same functionality repeatedly.

Time Efficiency: By using libraries, developers can save time and effort in implementing common tasks. This accelerates the development process and allows programmers to focus on solving specific problems rather than dealing with low-level details.

Consistency: Libraries provide standardized and consistent implementations for common tasks, ensuring that developers follow best practices and avoid common pitfalls.

Community Contribution: Python has a large and active community that develops and maintains numerous libraries. This fosters collaboration and allows developers to benefit from the collective knowledge and expertise of the community.

Performance Optimization: Many libraries are optimized for performance, taking advantage of efficient algorithms and data structures. Using these libraries can result in faster and more efficient code.

Domain-Specific Functionality: Python libraries often cater to specific domains or industries, providing specialized tools and functionality. For example, libraries like NumPy and pandas are widely used in data science and numerical computing.

Interoperability: Libraries often provide interfaces to interact with other tools, languages, or systems. This enhances the interoperability of Python with various technologies.

Open Source Ecosystem: Most Python libraries are open source, meaning that their source code is freely available. This fosters a collaborative and open development environment, allowing developers to inspect, modify, and contribute to the codebase.

Examples of popular Python libraries include NumPy (for numerical computing), pandas (for data manipulation and analysis), TensorFlow and PyTorch (for machine learning and deep learning), Flask and Django (for web development), and many more.

2. What is the difference between Numpy array and List?

NumPy arrays and Python lists are both used to store collections of elements, but there are several key differences between them. Here are some of the main distinctions:

Data Type:

List: A Python list can contain elements of different data types. It is a dynamic array that can hold any type of object.
NumPy Array: NumPy arrays are homogeneous, meaning all elements must be of the same data type. This allows for more efficient storage and operations on the array.
Performance:

List: Lists are generally slower than NumPy arrays, especially for large datasets, because they are dynamic and can store heterogeneous data.
NumPy Array: NumPy arrays are more efficient for numerical operations and large datasets due to their homogeneous nature and optimized, contiguous memory layout.
Memory Usage:

List: Lists consume more memory than NumPy arrays because they store additional information about each element, such as type and reference count.
NumPy Array: NumPy arrays have a more compact memory layout, resulting in lower memory usage.
Operations:

List: Lists support a variety of general-purpose operations, but they may not be as efficient for numerical and scientific computations.
NumPy Array: NumPy arrays provide a wide range of mathematical and logical operations that are vectorized, meaning operations can be applied element-wise without the need for explicit loops.
Syntax:

List: Lists are built into the core Python language and have a simple syntax for creation and manipulation.
NumPy Array: NumPy is a separate library, and its arrays are created using the numpy.array() constructor or other specialized functions. NumPy syntax allows for concise and expressive operations on arrays.

In [2]:
python_list = [1, 2, 3, 4, 5]

# NumPy Array
import numpy as np
numpy_array = np.array([1, 2, 3, 4, 5])

# Operations
python_list_squared = [x**2 for x in python_list]
numpy_array_squared = numpy_array**2

print(f"python_list_squared {python_list_squared}")  
print(f"numpy_array_squared {numpy_array_squared}") 


python_list_squared [1, 4, 9, 16, 25]
numpy_array_squared [ 1  4  9 16 25]


3. Find the shape, size and dimension of the following array?
[[1, 2, 3, 4]
[5, 6, 7, 8],
[9, 10, 11, 12]]

In [15]:
import numpy as np
arr=[[1, 2, 3, 4],
[5, 6, 7, 8],
[9, 10, 11, 12]]
numpy_array = np.array(arr)
numpy_array
print(f"shape : {numpy_array.shape}")
print(f"size : {numpy_array.size}")
print(f"dimension : {numpy_array.ndim}")

shape : (3, 4)
size : 12
dimension : 2


4. Write python code to access the first row of the following array?
[[1, 2, 3, 4]
[5, 6, 7, 8],
[9, 10, 11, 12]]

In [8]:
import numpy as np
arr1=[[1, 2, 3, 4],
[5, 6, 7, 8],
[9, 10, 11, 12]]
numpy_array1 = np.array(arr1)
numpy_array1[0]

array([1, 2, 3, 4])

5. How do you access the element at the third row and fourth column from the given numpy array?
[[1, 2, 3, 4]
[5, 6, 7, 8],
[9, 10, 11, 12]]

In [7]:
import numpy as np
arr2=[[1, 2, 3, 4],
[5, 6, 7, 8],
[9, 10, 11, 12]]
numpy_array2 = np.array(arr2)
print(f"element at the third row and fourth column from the given numpy array : {numpy_array2[2,3]}")

element at the third row and fourth column from the given numpy array : 12


6. Write code to extract all odd-indexed elements from the given numpy array?
[[1, 2, 3, 4]
[5, 6, 7, 8],
[9, 10, 11, 12]]

In [6]:
import numpy as np
arr3=[[1, 2, 3, 4],
[5, 6, 7, 8],
[9, 10, 11, 12]]
numpy_array3 = np.array(arr3)
odd_indexed_elements = numpy_array3[:, 1::2]  
# ":" selects all rows, "1::2" selects odd-indexed columns
print(f"Odd indexed elements :")
odd_indexed_elements

Odd indexed elements :


array([[ 2,  4],
       [ 6,  8],
       [10, 12]])

7. How can you generate a random 3x3 matrix with values between 0 and 1?

You can generate a random 3x3 matrix with values between 0 and 1 using the numpy.random.rand function from the NumPy library. Here's an example:

This code will create a 3x3 NumPy array (random_matrix) filled with random values between 0 (inclusive) and 1 (exclusive).

In [5]:
import numpy as np

# Generate a random 3x3 matrix with values between 0 and 1
np.random.rand(3, 3)


array([[0.33911401, 0.77040742, 0.58541189],
       [0.06614632, 0.46193036, 0.0685902 ],
       [0.58728404, 0.41995397, 0.22029011]])

8. Describe the difference between np.random.rand and np.random.randn?

The functions np.random.rand and np.random.randn are both used to generate random numbers in NumPy, but they have different behaviors and produce random numbers from different distributions.

np.random.rand:

This function generates random numbers from a uniform distribution over the interval [0, 1)
The generated values are uniformly distributed, meaning that each value has an equal chance of being selected.
The function takes dimensions as arguments to create an array of random values with the specified shape.

In [4]:
import numpy as np
np.random.rand(2, 3)


array([[0.56380825, 0.70800354, 0.3507325 ],
       [0.32421336, 0.58827374, 0.73719584]])

np.random.randn:

This function generates random numbers from a standard normal distribution (mean = 0, standard deviation = 1), also known as the standard Gaussian distribution.
The generated values are not uniformly distributed; instead, they follow a bell-shaped curve with higher density around the mean (0) and decreasing density as you move away from the mean.
Like np.random.rand, this function also takes dimensions as arguments to create an array of random values with the specified shape.
Example:

In [3]:
import numpy as np

np.random.randn(2, 3)



array([[-1.02040539, -0.26199947, -1.76971283],
       [-0.60086526,  0.91996374, -0.3326074 ]])

9. Write code to increase the dimension of the following array?
[[1, 2, 3, 4]
[5, 6, 7, 8],
[9, 10, 11, 12]]

In [49]:
import numpy as np
arr4=[[1, 2, 3, 4],
[5, 6, 7, 8],
[9, 10, 11, 12]]
numpy_array4 = np.array(arr4)
numpy_array5=np.expand_dims(numpy_array4,axis=1)
numpy_array5

array([[[ 1,  2,  3,  4]],

       [[ 5,  6,  7,  8]],

       [[ 9, 10, 11, 12]]])

10. How to transpose the following array in NumPy?
[[1, 2, 3, 4]
[5, 6, 7, 8],
[9, 10, 11, 12]]

In [2]:
import numpy as np
arr5=[[1, 2, 3, 4],
[5, 6, 7, 8],
[9, 10, 11, 12]]
numpy_array5 = np.array(arr5)
numpy_array5.T

array([[ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11],
       [ 4,  8, 12]])

11. Consi^er the following matrix:
Matrix A2 [[1, 2, 3, 4] [5, 6, 7, 8],[9, 10, 11, 12]]
Matrix B2 [[1, 2, 3, 4] [5, 6, 7, 8],[9, 10, 11, 12]]
Perform the following operation using Python1
,+ Index wise multiplication
]+ Matix multiplication
+ Add both the maticK
-+ Subtact matix B om 
+ Diide Matix B by A

In [9]:
import numpy as np
A2 = np.array([[1, 2, 3, 4],
               [5, 6, 7, 8],
               [9, 10, 11, 12]])

B2 = np.array([[1, 2, 3, 4],
               [5, 6, 7, 8],
               [9, 10, 11, 12]])

index_wise_multiplication = A2 * B2

# Matrix multiplication
matrix_multiplication = np.dot(A2, B2.T)  # Transposing B2 to match dimensions

# Addition of both matrices
matrix_addition = A2 + B2

# Subtraction of matrix B2 from A2
matrix_subtraction = A2 - B2

# Element-wise division of matrix B2 by A2
matrix_division = np.divide(B2, A2)

print("Index-wise Multiplication:")
print(index_wise_multiplication)

print("\nMatrix Multiplication:")
print(matrix_multiplication)

print("\nMatrix Addition:")
print(matrix_addition)

print("\nMatrix Subtraction:")
print(matrix_subtraction)

print("\nMatrix Division (Element-wise):")
print(matrix_division)

Index-wise Multiplication:
[[  1   4   9  16]
 [ 25  36  49  64]
 [ 81 100 121 144]]

Matrix Multiplication:
[[ 30  70 110]
 [ 70 174 278]
 [110 278 446]]

Matrix Addition:
[[ 2  4  6  8]
 [10 12 14 16]
 [18 20 22 24]]

Matrix Subtraction:
[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]

Matrix Division (Element-wise):
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


12. Which function in Numpy can be used to swap the byte order of an array?

In this example, the original array is created with a specified byte order using the dtype parameter. The byteswap method is then applied to swap the byte order of the array. The result is a new array with the byte order swapped.

Note that the dtype parameter in the array creation specifies the data type and byte order. In the example, '>i4' indicates a 32-bit integer with big-endian byte order.

Keep in mind that the byteswap method is applied in-place, meaning it modifies the original array. If you want to keep the original array unchanged, you may want to create a copy of the array before applying the byteswap method.

In [55]:
import numpy as np
original_array = np.array([1, 2, 3, 4], dtype='>i4') 
print("Original array:")
print(original_array)
swapped_array = original_array.byteswap()
print("\nSwapped array:")
print(swapped_array)

Original array:
[1 2 3 4]

Swapped array:
[16777216 33554432 50331648 67108864]


13. What is the significance of the np.linalg.inv function?

The np.linalg.inv function in NumPy is used to compute the multiplicative inverse (or matrix inverse) of a square matrix. The significance of this function lies in various mathematical and computational applications. 

Here are some key points regarding the significance of np.linalg.inv:

1.Solving Linear Systems of Equations
2.Eigenvalue and Eigenvector Calculations
3.Numerical Stability and Conditioning
4.

14. What does the np.reshape function do, and how is it used?

The np.reshape function in NumPy is used to change the shape of an array without changing its data. It allows you to specify the new shape of the array while keeping the total number of elements unchanged. Reshaping is a useful operation when you need to rearrange the dimensions of an array to fit a specific requirement or to match the expected input shape for certain functions.

The syntax of np.reshape is as follows:

numpy.reshape(a, newshape, order='C')

a: The array to be reshaped.
newshape: The new shape (tuple) that you want to assign to the array.
order: Optional parameter specifying the order of the elements. It can be 'C' for row-major (default) or 'F' for column-major.

In [64]:
import numpy as np

original_array = np.array([1, 2, 3, 4, 5, 6])
reshaped_array = np.reshape(original_array, (3, 2))

print("Original Array:")
print(original_array)

print("\nReshaped Array:")
print(reshaped_array)

original_array1 = np.array([[1, 2], [3, 4], [5, 6]])
reshaped_array1 = np.reshape(original_array1, (2, 3))

print("Original Array1:")
print(original_array1)

print("\nReshaped Array1:")
print(reshaped_array1)

original_array2 = np.array([1, 2, 3, 4, 5, 6])
reshaped_array2 = np.reshape(original_array2, (3, -1))

print("Original Array2:")
print(original_array2)

print("\nReshaped Array2:")
print(reshaped_array2)

Original Array:
[1 2 3 4 5 6]

Reshaped Array:
[[1 2]
 [3 4]
 [5 6]]
Original Array1:
[[1 2]
 [3 4]
 [5 6]]

Reshaped Array1:
[[1 2 3]
 [4 5 6]]
Original Array2:
[1 2 3 4 5 6]

Reshaped Array2:
[[1 2]
 [3 4]
 [5 6]]


15. What is broadcasting in Numpy?

Broadcasting in NumPy refers to the ability of NumPy to perform element-wise operations on arrays of different shapes and sizes during arithmetic operations. This enables NumPy to work with arrays of different shapes without explicitly reshaping them, making the code more concise and efficient.

In NumPy, for two arrays to be compatible for broadcasting, the size of the trailing dimensions (dimensions on the right) must either be the same or one of them must be 1. The smaller array is "broadcast" across the larger array so that they have compatible shapes for element-wise operations.

Broadcasting simplifies the syntax and improves the efficiency of array operations, as it eliminates the need for explicit reshaping or tiling of arrays before performing operations. However, it's important to understand the broadcasting rules to avoid unexpected behavior and errors. The rules ensure that the arrays are broadcastable and the dimensions are compatible for element-wise operations.

In [60]:
import numpy as np
scalar_value = 2
array = np.array([1, 2, 3])
result = scalar_value * array
print(result)

[2 4 6]


In [59]:
import numpy as np
array_2d = np.array([[1, 2, 3], [4, 5, 6]])
array_3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
result = array_2d + array_3d
print(result)

[[[ 2  4  6]
  [ 8 10 12]]

 [[ 8 10 12]
  [14 16 18]]]
